In [23]:
import numpy as np
import matplotlib.pyplot as plt 

#

# 1)

In [24]:
B = np.array([[3,-1],[-1,3]])
B_T_B = np.dot(B.T, B)

# calculte the eigenvalue and eigenvectors of BTB
eigenvalues, eigenvectors = np.linalg.eig(B_T_B)

# singular values 
singular_values = np.sqrt(eigenvalues)

B_T_B, eigenvalues, eigenvectors, singular_values

(array([[10, -6],
        [-6, 10]]),
 array([16.,  4.]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]),
 array([4., 2.]))

In [25]:
B = np.array([[3, -1], [-1, 3]])

eigenvalues, _ = np.linalg.eig(B)

eigenvalues

array([4., 2.])

#### 3a) 

In [26]:
# Circle topology
# Unweighted adjacency matrix

# Option 1: Manually enter the entries
Atilde = np.array(
         [[0,1,0,0,0,0,0,1],
          [1,0,1,0,0,0,0,0],
          [1,1,0,1,1,0,0,0],
          [0,0,1,0,1,0,0,0],
          [0,0,0,1,0,1,0,0],
          [0,0,0,0,1,0,1,0],
          [0,0,0,0,0,1,0,1],
          [1,0,0,0,0,0,1,0]])

# Option 2: or you can exploit the patterns
# Atilde = np.zeros((8,8))
# for i in range(8): # 
#     Atilde[i,(i+1)%8] = 1
#     Atilde[i,(i-1)%8] = 1
# Atilde[2,0] = 1
# Atilde[2,4] = 1

print('Unweighted adjacency matrix')
print(Atilde)
print(' ')

Unweighted adjacency matrix
[[0 1 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0]
 [1 1 0 1 1 0 0 0]
 [0 0 1 0 1 0 0 0]
 [0 0 0 1 0 1 0 0]
 [0 0 0 0 1 0 1 0]
 [0 0 0 0 0 1 0 1]
 [1 0 0 0 0 0 1 0]]
 


#### 3b)

In [27]:
# Find weighted adjacency matrix
# option 1: normalize columns with a for loop
A = np.zeros((8,8), dtype=float)
for k in range(8):
    norm = np.sum(Atilde[:,k])
    A[:,k] = Atilde[:,k] / Atilde[:,k].sum()
    
# option 2: normalize using numpy.sum() and broadcasting, in a single line
# A = ???

print('Weighted adjacency matrix')
print(A)

Weighted adjacency matrix
[[0.         0.5        0.         0.         0.         0.
  0.         0.5       ]
 [0.33333333 0.         0.5        0.         0.         0.
  0.         0.        ]
 [0.33333333 0.5        0.         0.5        0.33333333 0.
  0.         0.        ]
 [0.         0.         0.5        0.         0.33333333 0.
  0.         0.        ]
 [0.         0.         0.         0.5        0.         0.5
  0.         0.        ]
 [0.         0.         0.         0.         0.33333333 0.
  0.5        0.        ]
 [0.         0.         0.         0.         0.         0.5
  0.         0.5       ]
 [0.33333333 0.         0.         0.         0.         0.
  0.5        0.        ]]


#### 3c) and 3d)

In [28]:
# Power method

b0 = 0.125*np.ones((8,1))
print('b0 = ', b0)
print(' ')

b1 = A@b0
print('b1 = ', b1)
print(' ')









b0 =  [[0.125]
 [0.125]
 [0.125]
 [0.125]
 [0.125]
 [0.125]
 [0.125]
 [0.125]]
 
b1 =  [[0.125     ]
 [0.10416667]
 [0.20833333]
 [0.10416667]
 [0.125     ]
 [0.10416667]
 [0.125     ]
 [0.10416667]]
 


In [29]:
b = b0.copy()
for k in range(1000):
    b = A @ b
    
print('1000 iterations')
print('b = ',b)

1000 iterations
b =  [[0.11538462]
 [0.15384615]
 [0.23076923]
 [0.15384615]
 [0.11538462]
 [0.07692308]
 [0.07692308]
 [0.07692308]]


#### 3e) Explanation goes here.

The values in the PageRank vector represent the steady-state distribution of the importance across the nodes. The third nodes seems to be the most important since the value is greater than other nodes. Through the graph, more nodes are pointed to node 3

#### 4a)

In [30]:
# Hub topology

Atildehub = np.array([
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0.]])

print('Unweighted adjacency matrix')
print(Atildehub)
print(' ')

Unweighted adjacency matrix
[[0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0.]]
 


#### 4b)

In [31]:

# find weighted adjacency matrix

Ahub = Atildehub / Atildehub.sum(axis = 0)

print('Weighted adjacency matrix')
print(Ahub)

Weighted adjacency matrix
[[0.    0.    0.    0.    0.    0.    0.    0.    0.125]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.125]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.125]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.125]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.125]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.125]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.125]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.125]
 [1.    1.    1.    1.    1.    1.    1.    1.    0.   ]]


#### 4c) and 4d)

In [32]:
b0 = (1/9)*np.ones((9,1))
print('b0 = ', b0)
print(' ')

bhub1 = Ahub @ b0
print('bhub1 = ', bhub1)
print(' ')

bhub = b0.copy()
for k in range(1000):
    bhub = Ahub@bhub
    
print('1000 iterations')
print('bhub = ', bhub)
print(' ')








b0 =  [[0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]]
 
bhub1 =  [[0.01388889]
 [0.01388889]
 [0.01388889]
 [0.01388889]
 [0.01388889]
 [0.01388889]
 [0.01388889]
 [0.01388889]
 [0.88888889]]
 
1000 iterations
bhub =  [[0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]]
 


In [33]:
bhubr = b0.copy()
for k in range(100):
    bhubr = Ahub@bhubr
    
print('100 iterations')
print('bhubr = ',bhubr)

100 iterations
bhubr =  [[0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]]


In [42]:
bhubr = b0.copy()
for k in range(100):
    bhubr = Ahub@bhubr
    
print('100 iterations')
print('bhubr = ',bhubr)

100 iterations
bhubr =  [[0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]]


#### Complete 4e and 4f below.

In [44]:
bhubr = b0.copy()
for k in range(8):
    bhubr = Ahub@bhubr
    
print('100 iterations')
print('bhubr = ',bhubr)

100 iterations
bhubr =  [[0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]
 [0.11111111]]


we can find that when the iterations = 8, it converges

In [41]:
# no, every nodes are equally important
# Initialize the PageRank vector b0
# Function to perform the power method until convergence with a tolerance level
def power_method_until_convergence(adj_matrix, initial_vector, tolerance=1e-6):
    b_prev = initial_vector
    iterations = 0
    while True:
        # Perform the power method iteration
        b_next = adj_matrix @ b_prev
        
        # Check for convergence by comparing the change to the tolerance
        if np.max(np.abs(b_next - b_prev)) < tolerance:
            break
        
        b_prev = b_next
        iterations += 1
        
    return b_next, iterations

# Initial vector b0
b0 = np.ones((9, 1)) / 9

# Use the power method until convergence to find the specific number of iterations needed
final_vector, actual_iterations = power_method_until_convergence(Ahub, b0)

final_vector, actual_iterations


KeyboardInterrupt: 